### ISSUE TITLE
table style issue

### ISSUE THREAD

**Issue by dglzs** [emily123/smaless#13]
Can't see the table data when using low resolution.
![screenshot from 2015-12-08 10 12 07](https://cloud.githubusercontent.com/assets/9565372/11646017/7a1d5266-9d94-11e5-8e9c-a34b24c75c8d.png)
This should fix it. Adding min-width.
![screenshot from 2015-12-08 10 11 10](https://cloud.githubusercontent.com/assets/9565372/11646027/8f311480-9d94-11e5-91dc-fe37e4993bb4.png)

**Comment by daialihexiaoniu** [comment]
Already fixed issue in 22a38435fc693a17539145c8c5efc9aacbed74d2
